defaults: &defaults
  utf8: true
  morphology: stem_enru
  index_exact_words: 1
  indexed_models:
    - Entry

staging:
  <<: *defaults
  indices_location: "/var/www/fishrod/shared/db/sphinx"

development:
  <<: *defaults
